### DISCUSSION TITLE
Hello My Friends!

### DISCUSSION THREAD

**Discussion by arv-anshul** [arv-anshul/arv-anshul.github.io#1] [Announcements]
I have created a webpage for you only in website at [`/friends`](https://arv-anshul.github.io/friends) path where I can display your **informations like Name, Profession, Social Links, etc.**

🙏 You have to give me the required information of yours to display it on the webpage. **You can fill the below code block with your information:**

> [!WARNING]
>
> I will only add those whom I know very well because of some obvious region.

```yaml
name: # Your Name (शुभ नाम)
primaryUrl: # This can be your portfolio, linkedin profile URL or else
avatar: # Provide an URL to your profile pic
profession: # Your profession like College Student, Data Analyst, etc.
description: |
  Describe yourself in 100 to 500 **letters** (not words).
socials:
  # You can skip or add more social links here
  # For example: If have no LinkedIn profile then delete that section
  - title: Github Profile
    url: # Github profile url here
    icon: simple/github
  - title: LinkedIn Profile
    url: # Linkedin profile url here
    icon: simple/linkedin
  - title: Resume
    url: # Url of your resume to see/download
    icon: material/file-document
```

<details>
<summary>Example: Anshul Raj Veram's Information</summary>

```yaml
- name: Anshul Raj Verma
  primaryUrl: https://arv-anshul.github.io/about
  avatar: https://avatars.githubusercontent.com/u/111767754?v=4
  profession: Data Scientist
  description: |
    I am learning Data Science, ML and DL for 3 years. Very fluent in Python language,
    I had built many ML projects using frameworks like FastAPI and Streamlit. You can
    check all my [projects on website](https://arv-anshul.github.io/projects).
  socials:
    - title: Github Profile
      url: https://github.com/arv-anshul
      icon: simple/github
    - title: LinkedIn Profile
      url: https://linkedin.com/in/arv-anshul
      icon: simple/linkedin
    - title: Resume
      url: https://github.com/arv-anshul/arv-anshul/raw/main/resume_arv-anshul.pdf
      icon: material/file-document
    - title: Personal Website
      url: https://arv-anshul.github.io
      icon: simple/materialformkdocs
```

</details>

**😇 I am waiting for your response.**

**Comment by Wcowin** [comment]
Hello friend~🙌
```yml
- name: Wcowin
  primaryUrl: https://wcowin.work/
  avatar: https://s1.imagehub.cc/images/2024/02/02/91a767e93d1a344e44c69936464c583e.png
  profession: College Students
  description: |
    I am a junior from China. I love programming technology and have done some research on web development and AI large models. You can learn more about me through [my website](https://wcowin.work/).
  socials:
    - title: Github Profile
      url: https://github.com/Wcowin
      icon: simple/github
    - title: Personal Website
      url: https://wcowin.work/
      icon: simple/materialformkdocs
    - title: Email
      url: mailto:<wangkewen821@gmail.com> 
      icon: simple/material-email
```

**Reply by arv-anshul** [reply]
🎉 I have added your info on my website.

<img src="https://github.com/arv-anshul/arv-anshul.github.io/assets/111767754/47714665-73b8-46fb-951b-0dabac5072c6" width=400px title="Wcowin's Card Preview">

**Comment by somtoval** [comment]
```
name: Somto Ogbe
primaryUrl: https://www.linkedin.com/in/somto-ogbe/
avatar: https://s1.imagehub.cc/images/2024/04/27/a7230b57d5855ab7d231032e20572156.jpeg
profession: Student
description: |
  I am a Python Developer from Nigeria with keen interest in Backend Development and Data Science. I a very strong knowledge of Django, Flask and FastAPI for Web development, I also have a solid foundation in Machine Learning and Deep Learning especially Computer Vision. I just love to see things work!
socials:
  - title: Github Profile
    url: https://github.com/somtoval
    icon: simple/github
  - title: Linkedin profile
    url: https://www.linkedin.com/in/somto-ogbe/
    icon: simple/linkedin
  - title: Email
    url: mailto:<ogbesomto4@gmail.com>
    icon: material/file-document
```
